### ISSUE TITLE
How does inference works?

### ISSUE THREAD

**Issue by ostix360** [ByungKwanLee/TroL#7]
Hi, Thank you for your work!

You are using prop_index to identify which block is the first one and don't use past key value if it's the second one.

Am I correct with this?

if I am, during the second pass of the transformer block the past key value are not used anymore during generation so there is only one token is the attention mechanism...

Can you please help me to understand

**Comment by ByungKwanLee** [comment]
You are correct.

The past key values cannot be correctly utilized because they are saved in the key/value linear-layer(W_k, W_v) propagation before attention mechanism. Therefore, we cannot fully utilize second-propagation layer's past key value, but we instead only use first propagation's past key-value. Thanks to visual instruction training with layer traversing, it really works well in inference even without fully utilizing them.

**Comment by ostix360** [comment]
ok thanks for your answer
